version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: python_app
    volumes:
      - ./app:/app
    ports:
      - "8050:8050"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        python /app/load_data.py &&
        python /app/charts_luxury_loans.py
      "

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db
    depends_on:
      db:
        condition: service_healthy
      
volumes:
  pgdata: